SELECT H.HACKER_ID, H.NAME, COUNT(*) AS CNT
FROM HACKERS H
JOIN CHALLENGES C
ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CNT IN (SELECT SUB1.CNT
                FROM (SELECT HACKER_ID, COUNT(*) AS CNT
                     FROM CHALLENGES
                     GROUP BY HACKER_ID) AS SUB1
                GROUP BY SUB1.CNT
                HAVING COUNT(SUB1.CNT) = 1)
                OR
    CNT = (SELECT MAX(SUB2.CNT)
                FROM (SELECT HACKER_ID, COUNT(*) AS CNT
                     FROM CHALLENGES
                     GROUP BY HACKER_ID) AS SUB2)
ORDER BY CNT DESC, H.HACKER_ID ASC;
