SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W
JOIN WANDS_PROPERTY P
ON W.CODE = P.CODE
WHERE P.IS_EVIL = 0 AND W.COINS_NEEDED = (
    SELECT MIN(COINS_NEEDED)
    FROM WANDS W1
    JOIN WANDS_PROPERTY P1
    ON W1.CODE = P1.CODE
    WHERE P.AGE = P1.AGE AND W.POWER = W1.POWER
    )
ORDER BY W.POWER DESC, P.AGE DESC
